config/routes.rb
Timefliesby::Application.routes.draw do

  devise_for :users
  resource   :user

  resources :tasks do
    post 'switch_to', :on => :member
  end
  resources :tags

  root :to => 'welcome#index'

end

app/models/task.rb
require 'chronic_duration'

class Task < ActiveRecord::Base
  belongs_to :user
  has_many :tag_tasks
  has_many :tags, through: :tag_tasks
  before_create :set_stop_on_last
  validates_presence_of :user
  validates_associated :user, message: 'Bad user association' #Doesn't seem to do anything...
  validates_datetime :start, on_or_after: '2000-01-01 08:00'
  validates_datetime :stop, allow_blank: true
  validate :valid_stop
  default_scope order('start desc')

  def duration
    (self[:stop].blank? ? Time.zone.now.to_i : self[:stop].to_i) - self[:start].to_i
  end

  def switch_now(time = Time.zone.now)
    switch_at time
  end
  
  def switch_at(time)
    self[:start] = time
  end
  
  def set_stop_on_last
    previous_task = user.tasks.where("stop IS NULL").first
    if previous_task
      previous_task.stop = self[:start]
      previous_task.save!
    elsif self[:title] != 'Error: Time gap!'
      previous_task = user.tasks.where("stop < ?", self[:start]).first
      if previous_task
        gap = Task.create!(
          title:   'Error: Time gap!',
          start:   previous_task.stop,
          stop:    self[:start],
          user_id: self[:user_id]
        )
      end
    end
  end

  def switch_to(time = Time.zone.now)
    new_task = self.dup
    new_task.switch_now(time)
    new_task.stop = nil
    # deep copy associations
    # look into gem: deep_cloneable
    self.tags.each { |t| new_task.tags.push t }
    new_task
  end
  
  def valid_stop
    unless self[:stop].blank?
      if self[:stop] < self[:start]
        errors.add :stop, 'needs to be greater than start.'
      end
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all :include => :tags

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = current_user.tasks.new
    @tags = current_user.tags.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = current_user.tasks.find(params[:id])
    @tags = current_user.tags.all
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(params[:task])
    @task.switch_now if params[:commit] == 'Switch Now'

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        @tags = current_user.tags.all
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = current_user.tasks.find(params[:id])
    if params[:commit] == 'Switch Now'
      @task.switch_now
      params[:task] ||= {}
      params[:task][:stop] = @task.stop
    end

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        @tags = current_user.tags.all
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end

  # POST /tasks/1
  # POST /tasks/1.json
  def switch_to
    task = current_user.tasks.find(params[:id]).switch_to

    respond_to do |format|
      if task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully switched back to again.' }
        format.json { render json: task, status: :created, location: task }
      else
        format.html { redirect_to tasks_url, notice: 'Error! Please try again...' }
        format.json { render json: task.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  include DateTimeHelper
  
  def human_date_time(date_and_time)
    if date_and_time.nil?
      'Active'
    else
      editable_date_time date_and_time
    end
  end

end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 2 %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <% @tags.each do |tag| %>
      <label>
        <%= check_box_tag 'task[tag_ids][]', tag.id, @task.tags.include?(tag) %>
        <%= tag.name %><br />
      </label>
    <% end %>
    <%= hidden_field_tag 'task[tag_ids][]' %>
  </div>
  <div class="actions">
    <% if @task.new_record? %>
      <%= f.submit 'Switch Now' %>
    <% else %>
      <%= f.submit %>
    <% end %>
  </div>
  <hr>
  <h2>Fudge Factor</h2>
  <p>
    In this section you may manually enter the date and time.
  </p>
  <p>
    Yes, we provide automatic time tracking but sometimes, you know, you just have to FUDGE.
  </p>
  <p>
    No questions asked.
  </p>
  <div class="field">
    <%= f.label :start %><br />
    <%#= f.datetime_select :start %>
    <%#= f.text_field :start #Can't seem to find value! %>
    <%= text_field_tag 'task[start]', editable_date_time(@task.start), :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :stop %><br />
    <%#= f.datetime_select :stop %>
    <%#= f.text_field :stop #Can't seem to find value! %>
    <%= text_field_tag 'task[stop]', editable_date_time(@task.stop), :size => 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<% title 'Editing Task' -%>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/index.html.erb
<% title 'Tasks' -%>

<style type="text/css">
    .rightSpace {padding-right: 0.5em;}
    table div   {padding-right: 0.5em;}
    table th {                                                              text-align: left; }
    .wide { white-space: nowrap; }
    .number {                                                               text-align: right;}
    .dtstart  {                                     color: SteelBlue;}
    .dtstartHeader {                                color: SteelBlue;       text-align: right;}
    .duration {                                     color: DarkOliveGreen;  text-align: right;}
    .durationHeader {                               color: DarkOliveGreen;}
    .summary a:link    {text-decoration: none;      color: Maroon;}
    .summary a:visited {text-decoration: none;      color: Maroon;}
    .summary a:active  {text-decoration: underline; color: Maroon;}
    .summary a:hover   {text-decoration: none;      color: White;}
    .summaryHeader {                                color: Maroon;}
    .description {                                  color: BurlyWood;}
    .descriptionHeader {                            color: BurlyWood; }
    .tags    a:link    {                            color:     SkyBlue; }
    .tags    a:visited {                            color:     SkyBlue; }
    .tags    a:active  {                            color:        Blue; }
    .tags    a:hover   {text-decoration: none;      color: DarkSkyBlue; }
    .tagsHeader {                                   color:     SkyBlue; }
    .vevent { vertical-align: top; }
    h3 {font-size: 13px; margin-bottom: 0em;}
</style>

<table>
  <tr>
    <th>
      <div class="number">
        <span class="durationHeader">Duration,</span>
        <span class="wide dtstartHeader">Start</span>
      </div> 
    </th>
    <th>
      <div>
        <span class="summaryHeader">Title</span>
        <span class="descriptionHeader">Description,</span>
        <span class="tagsHeader">Tags</span>
      </div>
    </th>
    <th>
      <%= link_to 'New', new_task_path %>
    </th>
  </tr>
<% current_date = 'Ongoing' %>
<% @tasks.each do |task| %>
  <% if task.stop.nil? %>
    <tr>
      <td>
        <div class="durationHeader number">
          <h3>Ongoing</h3>
        </div>
      </td>
      <td></td>
      <td></td>
    </tr>
  <% elsif current_date != human_longer_date(task.start) %>
    <% current_date = human_longer_date(task.start) %>
    <tr>
      <td>
        <div class="dtstartHeader">
          <h3>
            <%= current_date %>
          </h3>
        </div>
      </td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
  <tr class="vevent">
    <td>
      <div class="wide number duration">
        <span class="value-title" title="<%= microformats_duration task.duration %>"> </span>
        <%= human_duration task.duration %>
      </div>
      <div class="wide number dtstart">
        <span class="value-title" title="<%= microformats_date_time task.start %>"> </span>
        <%= human_time task.start %>
      </div>
    </td>
    <td>
      <div>
        <span class="summary">
          <%= link_to task.title.presence || '-- No Title! --', task, :class => 'url' %>
        </span>
        <span class="description">
          <%= task.description %>
        </span>
      </div>
      <div class="tags">
        <% task.tags.each do |tag| %>
          <%= link_to tag.name, tag, 'rel' => 'tag' %>
        <% end %>
      </div>
    </td>
    <td>
      <%= form_for task, :url => switch_to_task_path(task), :html => { :method => :post } do |f| %>
        <span class="actions">
          <%= f.submit 'Again', :title => 'Switch to this again' %>
        </span>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/tasks/new.html.erb
<% title 'New Task' -%>

<%= render 'form' %>

<%= link_to 'Back to Tasks', tasks_path %>

app/views/tasks/show.html.erb
<% title 'Task' -%>

<p id="notice"><%= notice %></p>

<div class="vevent">
  <p>
    <b>Title:</b>
    <span class="summary">
      <%= @task.title %>
    </span>
  </p>
  
  <p>
    <b>Tags:</b>
    <span class="tags">
      <% @task.tags.each do |tag| %>
        <%= link_to tag.name, tag, 'rel' => 'tag' %>
      <% end %>
    </span>
  </p>

  <p>
    <b>Duration:</b>
    <span class="duration">
      <span class="value-title" title="<%= microformats_duration @task.duration %>"> </span>
      <%= human_duration @task.duration %><br>
    </span>
  </p>

  <p>
    <b>Start:</b>
    <span class="dtstart">
      <span class="value-title" title="<%= microformats_date_time @task.start %>"> </span>
      <%= human_date_time @task.start %>
    </span>
  </p>

  <p>
    <b>Stop:</b>
    <span class="dtend">
      <span class="value-title" title="<%= microformats_date_time @task.stop %>"> </span>
      <%= human_date_time @task.stop %>
    </span>
  </p>

  <p>
    <b>Description:</b>
    <span class="description">
      <%= @task.description %>
    </span>
  </p>

  <%= link_to 'Edit', edit_task_path(@task), :class => 'url' %> |
  <%= link_to 'Destroy', @task, :confirm => 'Are you sure?', :method => :delete %> | 
  <%= link_to 'Back to Tasks', tasks_path %>
</div>